<?php

class InstallUseModempollerNmsprime extends BaseMigration
{
    protected $tablename = '';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        /*
         * disable unneeded snmp agent
         * one poller processes is sufficient to analyze the files generated by modempoller-nmsprime
         * don't let cacti check modems availability as we get the info implicitly via modempoller-nmsprime
         */
        DB::connection('mysql-cacti')->statement("REPLACE INTO settings VALUES ('enable_snmp_agent','')");
        DB::connection('mysql-cacti')->statement("UPDATE poller SET processes = 1 WHERE name = 'Main Poller'");
        DB::connection('mysql-cacti')->statement("UPDATE host SET availability_method = 0 WHERE description LIKE 'cm-%'");
        system("sed -i 's/^[^#]/#/' /etc/cron.d/cacti");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
}
