<?php

class InstallUseModempollerNmsprime extends BaseMigration
{
    protected $tablename = '';

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        require_once '/etc/cacti/db.php';
        /*
         * disable unneeded snmp agent
         * one poller processes is sufficient to analyze the files generated by modempoller-nmsprime
         * don't let cacti check modems availability as we get the info implicitly via modempoller-nmsprime
         */
        system("echo \"REPLACE INTO settings VALUES ('enable_snmp_agent',''); UPDATE poller SET processes = 1 WHERE name = 'Main Poller'; UPDATE host SET availability_method = 0 WHERE description LIKE 'cm-%';\" | mysql -u $database_username -p$database_password $database_default");
        system("sed -i 's/^[^#]/#/' /etc/cron.d/cacti");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
}
