<?php

use Illuminate\Database\Migrations\Migration;

class CreateTRCClassTable extends BaseMigration
{
    // name of the table to create
    protected $tablename = 'trcclass';

    /**
     * Run the migrations.
     *
     * ATTENTION: TRCClass has been moved to ProvVoip (needed on PhonenumberManagement in each case!)
     *				if later changes are neccessary: update at ProvVoip!
     *				This migration is kept here for backward compatibility reasons…
     *
     * @return void
     */
    public function up()
    {
        // this up() is not used anymore – so we deleted all content
        // on new installations this table will be generated by the ProvVoip version of this migration
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        // this has to be left here to be roll-backable on older installations having migrated with this version…
        // but: we have to check if this table still exists – could have been deleted from rolling back ProvVoip
        Schema::dropIfExists($this->tablename);
    }
}
